### ISSUE TITLE
[QUESTION] How to play single player?

### ISSUE THREAD

**Issue by RetroGameTalk** [Krokodyl/dokapon-english#1]
How to play single player? I only see option for 3 or 4 human players. Any help?

**Comment by Krokodyl** [comment]
On the screen that says "Player 1 - Human" / "Player 2 - Human" etc. you can hit right or left to select AI with weak/normal/hard level for each one.

**Comment by RetroGameTalk** [comment]
Thanks i would have never figured it out. Very unintuitive.
