### ISSUE TITLE
game crashing when browsing second magic shop

### ISSUE THREAD

**Issue by Sarajiko** [Krokodyl/dokapon-english#3]
After looking at the spell CELERITY under Attack Magic in the magic shop of the second area the game crashes afterwards.

The description of CELERITY is slightly scrambled. It shows the text "breaks your opponent's equipment". The second line "Has no effect on monsters." seems to be scrambled together with "Highest fire damage" 

I looked up the tables and it seems Table 7 Line 720 lacks the closing {EL} tag which causes the game to load the next entry in the same box.
![CELERITY](https://user-images.githubusercontent.com/80350428/110510254-4e17ce00-8103-11eb-9320-e972fe1dd99d.PNG)

**Comment by Krokodyl** [comment]
Hi,
From a quick glance, your analysis seems right, the missing end of line tag has this effect.
I will make the change when I find the time.
Thank you
